# Generated by Django 5.2.6 on 2025-09-27 16:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentaccount_date_joined_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID must be in the format YY-NNNN-NNN (e.g., 23-6385-642).', regex='^\\d{2}-\\d{4}-\\d{3}$')]),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID must be in the format YY-NNNN-NNN (e.g., 23-6385-642).', regex='^\\d{2}-\\d{4}-\\d{3}$')])),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
